---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgCwIyp+LAKlHXTrESAzO5QP4JdR0wtU5504UX95N7/E/cYeOxFOYR8/Mr5nGJAfNtqsAGBP9ugebL4iknfL6gLzq1oH05H+/285FGN85i5Mospt4C7FhemFIk7b935LIZ3vB/GXm01l5IAhFR17L7BbjxuNB8CNLiXJhcffAMpj8p6t/WlUeJ6RVIhMHXnW3wUyd+z6zVYFq9EPsYIf2bi15wr99+ccU3666cSYFJ/CWCchBwQ3vmJrFGVNxgzY72cQUGz9fYCxhfw87WFGwC+eYXT8lawNp9bIw6F+IC7s5FAE0hQOdj1d/dQYep51I19+dzr69RjH/v5hb0ENgMbhDoO7m3kvKXf99zn4qbsLBAxGQvcaFZY3xC4Ow7fM4YNr+iTq7QXHdG0G44ekURAhW/ATxcUe3IGywo4E2yiY/PuT0zv4iOkdItLSLr31xnzAVP+xgsG30U41ItQWwObFwOJg/sB0OPeXTS/z257QArW9VtxGNHpaxEIWLGz7seYbL4Fkw0Blht0O+rsOC3YkWG8FWWe/wcRpBwW7uANfQ+BSKvtgTjjjv6DJGHKbDSBa9Am4gNaTa4yoL+mjqpxCcVHsr6MxADypqR08g1aXvn0JxyeLUOzgS6QzsX5KAwxtWBKT7BzssChvh4Di8xfyrQroz9+ZB3hJw80KavpvHfOKUdPaZf169UONE1TsMOytHhaP8MadPYWSzPhnptahedM+N9M3m66EygUXnm/LH2qwbX27Y7PVxB+Mu+HlyjY3UbC29gqsdLPZf+Dj/WvOp15C1cfNtaZjBux/KIOJ3fmLds1ZSKOizS8aXBDxmrPKGYH6qVoS/Yz2bqpl9Q==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson