# Nombre del Pipeline
name: CI Pipeline

# Significa cuando alguien haga push a main o develop se ejecutara el pipeline
on: 
  push:
    branches:
      - main
      - develop
jobs:

  # LINTING (funciona para verificar la calidad del codigo)
  # Evita que codigo mal formado llegue a producción
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install lint tools
        run: |
          pip install ruff black
      
      - name: Run Ruff Linter
        run: |
          ruff check .
      
      - name: Check formatting
        run: |
          black --check .

  # SECUTIRY SCAN (Buscar vulnerabilidades en dependencias)
  security:
    runs-on: self-hosted
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install security scanner
        run: |
          pip install bandit
      
      - name: Run Bandit security scan 
        run: |
          bandit -r src
  

  
  # Github crea una maquina virual Linux para ejecutar el pipeline
  test:
    needs: security
    runs-on: self-hosted

    strategy:
      # Probar verias versiones de Python
      matrix:
        python-version: ["3.10","3.11","3.12"]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/testdb
      ENV: test

    steps:
      - name: checkout code
        uses: actions/checkout@v4

        # Instalamos Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      # Instalamos dependencias
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Wait Postgres
      - name: Wait for postgres
        run: |
          sleep 10
      
      # Ejecutamos tests con cobertura
      - name: Run tests
        run: |
          pytest --cov=src --cov-report=xml
      
      # Save coverage (Guarda resultados del pipeline)
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          # name: coverage-report-${{ matrix.python-version }} con nombre unico
          name: coverage-report
          path: coverage.xml
          overwrite: true
  
  # Solo corre si test pasa
  # Si los test fallan el buil no corre
  build:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
        # Construimos la imagen, esto se hara despues con Harbor
        # Por el momento solo creara la imagen Docker dentro de la VM
      - name: Build Docker image
        run: |
          docker build -t poc-cicd-app:ci .
      
      # TRIVY
      # Trivy escanea vulnerabilidades del OS
      # vulnerabilidades en dependencias
      # vulnerabilidades en Docker images
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: poc-cicd-app:ci
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  ############################################
  # NOTIFICATION
  ############################################
