# Nombre del Pipeline
name: CI Pipeline

# Significa cuando alguien haga push a main o develop se ejecutara el pipeline
on: 
  push:
    branches:
      - main
      - develop
jobs:

  # LINTING (funciona para verificar la calidad del codigo)
  # Evita que codigo mal formado llegue a producción
  lint:
    runs-on: self-hosted
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create venv
        run: |
          python -m venv venv
      
      - name: Install lint tools
        run: |
          source venv/bin/activate
          pip install ruff black
      
      - name: Run Ruff Linter
        run: |
          source venv/bin/activate
          ruff check .
      
      - name: Check formatting
        run: |
          source venv/bin/activate
          black --check .

  # SECUTIRY SCAN (Buscar vulnerabilidades en dependencias)
  security:
    runs-on: self-hosted
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Create venv
        run: |
          python -m venv venv

      - name: Install Bandit
        run: |
          source venv/bin/activate
          pip install bandit
      
      - name: Run Bandit security scan 
        run: |
          source venv/bin/activate
          bandit -r src
  

  
  # Github crea una maquina virual Linux para ejecutar el pipeline
  test:
    needs: security
    runs-on: self-hosted

    strategy:
      # Probar verias versiones de Python
      matrix:
        python-version: ["3.10"]
        #python-version: ["3.10","3.11","3.12"]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/testdb
      ENV: test

    steps:
      - name: checkout code
        uses: actions/checkout@v4

        # Instalamos Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create venv
        run: |
          python -m venv venv
      
      # Instalamos dependencias
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Wait Postgres
      - name: Wait for postgres
        run: |
          sleep 10
      
      # Ejecutamos tests con cobertura
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --cov=src --cov-report=xml
      
      # Save coverage (Guarda resultados del pipeline)
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          # name: coverage-report-${{ matrix.python-version }} con nombre unico
          name: coverage-report
          path: coverage.xml
          overwrite: true
  
  # Solo corre si test pasa
  # Si los test fallan el buil no corre
  build:
    needs: test
    runs-on: self-hosted

    env: 
      IMAGE_NAME: ${{ secrets.HARBOR_URL }}/poc/poc-cicd-app
      VERSION: 1.0.${{ github.run_number }} # Es un contador automatico del workflow
      COMMIT_SHA: ${{ github.sha }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4 # Descagamos el repositorio del runner
      
      # cON --password-stdin es para permitir enviar la contraseña por entrada estandar
      - name: Login Harbor
        run: |
          echo "${{ secrets.HARBOR_TOKEN }}" | docker login \
            ${{ secrets.HARBOR_URL }} \
            -u "${{ secrets.HARBOR_USER }}" \
            --password-stdin 
        
        # Construimos la imagen usando el DockerFile (-t es para definir el tag inicial de la imagen)
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$VERSION .

      - name: Tag images
        run: |
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:$COMMIT_SHA
      
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$COMMIT_SHA
      
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.HARBOR_URL }}/poc/poc-cicd-app:${{ env.VERSION }}
          format: table
          exit-code: 1
          ignore-unfixed: true # Ignora vulnerabilidades con parche disponible
          vuln-type: 'os,library' # Escane paquetes del sistema y dependencias del lenguaje
          severity: 'CRITICAL,HIGH' # Solo falla cuando hay vulnerabilidades clav es


  #   needs: test
  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
        
  #       # Construimos la images
  #       # Por el momento solo creara la imagen Docker dentro de la VM o host self-hosted runner
  #     - name: Build Docker image
  #       run: |
  #         docker build -t poc-cicd-app:ci .
      
  #     # TRIVY
  #     # Trivy escanea vulnerabilidades del OS
  #     # vulnerabilidades en dependencias
  #     # vulnerabilidades en Docker images
  #     - name: Scan Docker image with Trivy
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         image-ref: poc-cicd-app:ci
  #         format: table
  #         exit-code: 1
  #         ignore-unfixed: true
  #         vuln-type: 'os,library'
  #         severity: 'CRITICAL,HIGH'
  ############################################
  # NOTIFICATION
  ############################################
